### ISSUE TITLE
React JavaScript Milagro Widget

### ISSUE THREAD

**Issue by JohnMcW** [apache/incubator-milagro-crypto-c#23]
As user we want to provide a react.js component and a react.native component
in a way that Milagro will seamless integrate in any react based website. The code is already present in the javascript libraries. Just create a react component with the updated javascript library and test the,.

**Comment by JohnMcW** [comment]
This issue was https://issues.apache.org/jira/browse/MILAGRO-36 in Apache Jira - that issue will be closed presently

**Comment by howardkitto** [comment]
I have started working on this

**Comment by giorgiozoppi** [comment]
We close this..since nobody is longer working after 3 years.
