### ISSUE TITLE
FP_ZERO redefintion in amcl.h prevents compiling

### ISSUE THREAD

**Issue by JohnMcW** [apache/incubator-milagro-crypto-c#25]
Enviroment : gcc-7 7.3.0-27ubuntu1~18.04
Additional Libraries: Protocol Buffers. 
![Screenshot%20from%202019-03-31%2014-54-11](https://user-images.githubusercontent.com/95958/61303115-ddf65f00-a7de-11e9-85cd-b40902adeeae.png)
The current amcl crypto that i am using as backend, redefine FP_ZERO, that it is by default defined in math.h in libgcc that it is included in protocol buffers, since i am rewriting dta and rps with protobuf3 using amcl.
This leads to users to be not able to compile. The solution is quite trivial, just put
#ifndef FP_ZERO
#define FP_ZERO 0
#endif
This will solve the issue.
Best Regards,
Giorgio

**Comment by JohnMcW** [comment]
This issue was https://issues.apache.org/jira/browse/MILAGRO-23 in Apache Jira - that issue will be closed presently

**Comment by kealan** [comment]
This issue has already been spotted and fixed. Please use the develop branch until we release the code.
