### ISSUE TITLE
Miller loop test fail in Zenroom using BLS383 and BLS381

### ISSUE THREAD

**Issue by jaromil** [apache/incubator-milagro-crypto-c#32]
Hi there! glad to find back your repo here, pity for the commit history, I guess per ASF policy...

In Zenroom I'm including milagro at the version you tagged as 4 before removing this repo.

Today I was trying to check this new repository out and see if it fits seamlessly and passes all my tests. I really appreciate the ECP_ZZZ_toOctet flag for compression! However I get an errror.

As per subject, one of my ECP2 pairing tests fails, more precisely the one where I check this property:
```
miller(sQ,P) = miller(Q,P)^s
```
where `Q` is an ECP2 point derived from the curve's generator multiplied by a random BIG modulo curve's order
and `P` is an ECP1 point derived the same way

I'm using your current master branch and BLS383. Will soon check out 381 too.

I understand this should pass and it did pass with the "older" version of milagro which you can see in zenroom's repository. Is there anything you can think of about this issue?
thanks,
ciao

**Comment by kealan** [comment]
Hi Yes it is pity what happened with the commit history. We should have been developing on Apache from the start.

The project is hoping to make a release next week or at least start the process. Until then I would not look at the master branch but use the develop branch. 

I would be concerned if what you say doesn't work on the develop branch. It would be strange as the tests pass and the schemes built on top of pairing work. 

Also, is there an argument for reducing the number of curves. What do we need BLS383 when we have BLS12-381? Do we need to support BN254CX etc.?

**Comment by jaromil** [comment]
Hi Kealan, thanks for your reply! about the Miller Loop test on BLS383 (the only curve I can easily test right now in Zenroom), I confirm the non-deterministic failure of the test (passes once ever 4 or 5 execution times) also with the current develop branch. Zenroom code used for the test:
```lua
ECP = require('zenroom_ecp')
ECP2 = require('zenroom_ecp2')
G1 = ECP.generator()
G2 = ECP2.generator()
r = ECP.order()
-- generate a big random number of maximum INT size and apply modulo of the curve's order  
function R() return INT.modrand(r) end
P1 = G1 * R() -- Pick a random point in G1
Q1 = G2 * R() -- Pick a random point in G2
-- Test that miller(sQ,P) = miller(Q,P)^s, s random"
s = R()
g1 = ECP2.miller( Q1*s, P1)
g2 = ECP2.miller( Q1, P1)^s
assert(g1 == g2)
```

About the other points, in the hope are useful, hereby my opinions:
1. Publish an annotated diff of the repository history pre and post ASF, eliminating cosmetic changes (whitespace and emails) and build system changes, to focus on what changes in the code between the last commit on "version 4" and the first commit on the new repo.
2. Milagro is wonderful in many ways, one of them is that it is a generic base library for crypto providing choice among a number of curves. If it is no effort to maintain "old" curves then I recommend keeping them around. It is also what made OpenSSL dominate the scene so far so this is mostly a strategic choice, if at par with effort.
2a. If there would be anything that I'd shave off Milagro that would be RSA.

**Comment by jaromil** [comment]
Just tested 2.0.0 release using curve BLS381 and confirm the above test still fails, but without indeterminism: it fails always. Will keep investigating, insights welcome.

**Comment by jaromil** [comment]
I found the problem on my side: using the `fp12_pow` function instead of the `pair_zzz_gtpow` for the exponentiation of the ate pairing result. Sorry for the noise and thanks for your patience.
