### ISSUE TITLE
Difference with skair39/milagro-crypto-c

### ISSUE THREAD

**Issue by GuillaumeCisco** [apache/incubator-milagro-crypto-c#37]
Hello guys, is there any difference between you work and this one: 
https://github.com/skair39/milagro-crypto-c
Looks like yours is the official and the other a old one.

Could you confirm me that?

**Comment by kealan** [comment]
Yes that seems to be an old version of this code.

**Comment by GuillaumeCisco** [comment]
Thanks for the precision
