### ISSUE TITLE
Python test wrappers - python 3?

### ISSUE THREAD

**Issue by GuillaumeCisco** [apache/incubator-milagro-crypto-c#39]
Are current python tests for python wrappers compatible with python 3?
It looks like not :/
Can someone confirm me that?

Thanks,

**Comment by kealan** [comment]
Hi That is the case. The only module that works with python3 is bls_ZZZ.py.in. The plan would be to move all the code to Python 3. If you want to do this yourself then it would be a great contribution.

**Comment by GuillaumeCisco** [comment]
Thanks for the confirmation.
By the way, what's the `_ZZZ` suffix stands for?

I've already inspected it and it worked with python3 on https://github.com/skair39/milagro-crypto-c
I will adapt my patch to this project.

**Comment by kealan** [comment]
ZZZ is the curve that the library builds with.
