### ISSUE TITLE
ZKP-Enabled Ephemeral APIs 

### ISSUE THREAD

**Issue by nathanawmk** [apache/incubator-milagro-crypto-c#68]
Hello! I am an API architect and I am exploring and contributing to solutions around ZKP-Enabled Ephemeral APIs that is an extension of OAuth Access Token Expiry mechanism.

Though we are able to expire token and revoke access, we want to all together expire the data that was returned by the API call. 

Is ZKP-Enabled Ephemeral APIs something I can contribute to?

**Comment by kealan** [comment]
Hi 

I am not sure I understand. Are you proposing to add an API level to this project or use this code in another project?

**Comment by nathanawmk** [comment]
Yes, somewhat. But more importantly to develop APIs that leverage ZKP so that the consumers/clients who use these APIs will not actually have these the API data. They use the APIs without actually holding the data.

**Comment by kealan** [comment]
In my opinion, using this protocol for API authentication is probably not a good idea given the CPU load that would be on the server side.

**Comment by nathanawmk** [comment]
I disagree. the future of APIs will be one that is ephemeral and ZKP enabled. If there are such projects around, we can and should collaborate on it.

**Comment by jaromil** [comment]
Hi! aren't you talking about a new project using milagro? this software is a *library*. FYI I am also working on ZKP and occasionally APIs, happily embedding milagro into dev.zenroom.org and in recent research we are addressing revokation strategies.

**Comment by giorgiozoppi** [comment]
No action items. We close this.
