### ISSUE TITLE
Rust Based Crypto Library (AMCL)

### ISSUE THREAD

**Issue by nathanawmk** [apache/incubator-milagro-crypto-c#69]
Because the Rust programming language has better memory safety safeguards, is Rust Based Crypto Library (AMCL) in the pipeline/consideration?

**Comment by kealan** [comment]
Hi There is work on the Rust library being done in this repo
https://github.com/apache/incubator-milagro-crypto-rust

**Comment by nathanawmk** [comment]
Apologies I may have missed that out. many thanks. What are the contribution guidelines?

**Comment by kealan** [comment]
I am really involved in that project. I would just fork and make a feature branch and then make a PR.
This is main dev 

https://github.com/apache/incubator-milagro-crypto-rust/issues/created_by/kirk-baird

**Comment by nathanawmk** [comment]
cool. lets collaborate.

**Comment by giorgiozoppi** [comment]
we have this i close this issue
